---
- hosts: dev
  user: aniketb
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=present
    - name: start Apache
      action: service name=apache2 state=started

